### PR TITLE
bots no longer fire through walls

### PR DESCRIPTION
**Pull request by bmorel**

### CODE REVIEW

**Comment by TheAssassin** [comment]
Seems to work, quite some improvement. More testing required, though.

**Comment by bmorel** [comment]
it's a very old thing, really, I don't know why I never pushed this. Looks like I have bunch of refactoring branches on disk, not sure if worth the time to get those, I don't remember having more fixes/features

**Review by TheAssassin — APPROVED** [review]
Seems to work. I'd like to hear @voidanix's thoughts, though.

**Review by voidanix — APPROVED** [review]
Code style is a little broken with that 193 columns line, but otherwise LGTM and seems to supersede #185 as the bots "shake around" less when no target is in sight.

**Pull request merged**
