### PR TITLE
Replace remaining commands *gui -> *_ui

### PR DESCRIPTION
**Pull request by robalni**
Since we're moving from *gui commands to *_ui I thought it would be a good idea to complete that move. Doing this fixes the "TIP: press * to open this menu at any time" texts for e.g. the help menu, that would not show any key since there was a mismatch between *gui and *_ui.

Screenshot of menu not showing correct tip:
screenshot of bug

### CODE REVIEW

**Comment by MoonPadUSer** [comment]
I think the reason we didn't change that was because it is used in inline-cubescript inside of C++ somewhere and also in custom-scripts (which we still need to write a compatibility layer for O_o)

**Comment by robalni** [comment]
What is used where?

**Comment by MoonPadUSer** [comment]
newgui, cleargui, etc

**Comment by MoonPadUSer** [comment]
but I am not sure about that anymore, I'll have to check it

**Comment by MoonPadUSer** [comment]
ok, I just looked it up, I was wrong

**Pull request merged**
