### PR TITLE
Support generation of NSIS installer with CPack

### PR DESCRIPTION
**Pull request by TheAssassin**
Will be used in the release repository to generate proper installers.

### CODE REVIEW

**Review by voidanix — CHANGES_REQUESTED** [review]
Please update the ICO file path to what #263 defined, otherwise looks good.

**Comment by voidanix** [comment]
While you are at it, can you also:

- Add `CPACK_PACKAGE_VENDOR`
- Replace `CPACK_PACKAGE_HOMEPAGE` with `CPACK_PACKAGE_HOMEPAGE_URL`

The possibility of using `CPACK_PACKAGE_ICON` (instead of `CPACK_NSIS_MUI_ICON`) should also be explored, especially if it could be used by both NSIS and future installers for other platforms.

**Comment by TheAssassin** [comment]
Will do. Investigating the addition of `DragNDrop` support for macOS `.dmg` bundles, which makes use of some of these, too.

**Comment by TheAssassin** [comment]
For the record, I already evaluated `CPACK_PACKAGE_ICON` extensively, it doesn't replace `CPACK_NSIS_MUI_ICON` and breaks other stuff. I'd stay away from it.

**Review by voidanix — APPROVED** [review]

**Pull request merged**
